version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticket_system
      MYSQL_USER: django_user
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - django-network

  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql
      DB_NAME: ticket_system
      DB_USER: django_user
      DB_PASSWORD: my-secret-pw
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG: "True"
      SECRET_KEY: "your-secret-key"
      ALLOWED_HOSTS: "*"
    depends_on:
      - mysql
      - redis
    command: >
      /bin/bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput || true &&
      python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - django-network

volumes:
  mysql_data:

networks:
  django-network:
    driver: bridge
